### ISSUE TITLE
Leave room errors

### ISSUE THREAD

**Issue by rts-gordon** [thruster-rs/thruster-socketio#10]
Hi @trezm ,
  I test the socket.leave() code as follows, but there are two errors those occur random. Would you like to spend time to fix those, thank you very much.

```
async fn leave_room(mut socket: SocketIO, value: String) -> Result<(), ()> {
    socket.leave(&value).await;
    Ok(())
}
```  

Error 1:
```
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', C:\Users\AUser\.cargo\registry\src\github.com-1ecc6299db9ec823\thruster-socketio-0.1.8\src\rooms.rs:54:47
```

Error 2:
```
thread 'tokio-runtime-worker' panicked at 'removal index (is 1) should be < len (is 1)', library\alloc\src\vec\mod.rs:1349:13
```

**Comment by trezm** [comment]
Should be resolved by https://github.com/thruster-rs/thruster-socketio/pull/12, try using master and let me know!

**Comment by rts-gordon** [comment]
Hi @trezm .
   Thanks for your fix so quickly.
   I download the new code, but there are still panics, I found the pattern:

  1、When leave an non-exist room, the panic is:
```
2021-06-11T09:35:45.372007500+10:00 WARN socketio::socketio::socketio - Socket(7kUkyLQiKrwHb4WomyE3C7Pn175hQe) leave an non-exist room(ssssss).
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', C:\Users\AUser\.cargo\git\checkouts\thruster-socketio-1041f7878b44477b\5f75108\socketio_middleware\src\rooms.rs:54:47
```
 
  2、When leave an exist room， the panic as follows, but I didn't found the code: library\alloc\src\vec\mod.rs
```
2021-06-11T09:42:06.460141500+10:00 DEBUG socketio::socketio::socketio - Socket(9uqvyFdSR4UzA9SlhoftuET4T0lgfF) leave room(zzz), room member number = 0
thread 'tokio-runtime-worker' panicked at 'removal index (is 2) should be < len (is 2)', library\alloc\src\vec\mod.rs:1349:13
```

And would you like to give a tag on master branch, or publish to crate.io when you fix the issue,  I want to depend on a special tagged code.

Thanks again.

**Comment by trezm** [comment]
I'll take a look at these when I get a chance! Sorry for the delay, things are a bit busy right now!
