### ISSUE TITLE
How to dispatch message from kafka to socketio ?

### ISSUE THREAD

**Issue by rts-gordon** [thruster-rs/thruster-socketio#11]
Hi @trezm,

  My program reads message from Kafka,   then dispatch to frontend via socketio. I learned a lot of "thrust-socketio",  but I didn't found a way to do this. Is there a function like "io.to(room).emit(room, message)" that javascript socketio does?

  Will you please give me a example: how to dispatch message from kafka to socketio rooms? Thank you very  much.

**Comment by trezm** [comment]
Check out the [redis_pubsub](https://github.com/thruster-rs/thruster-socketio/blob/master/socketio_middleware/src/redis_pubsub.rs) module for an example on how to share messages between separate server instances. The default is to use redis, but you can adapt this approach to use kafka if you like. If you do, open up a PR and we'll add it to the library.

If you already have the `io` object and you're responding, for example, try out [io.emit_to(roomId, event, message)](https://github.com/thruster-rs/thruster-socketio/blob/master/socketio_middleware/src/socketio.rs#L172)

**Comment by CHCP** [comment]
I try to call socket.emit_to(roomId, event, message) method, but I can't get any socket object from another separate context, so I will try kafka adapter.

**Comment by rts-gordon** [comment]
I try to call socket.emit_to(roomId, event, message) method, but I can't get any socket object from another separate context.  

Would you like to implement  a emit_to(roomId, message) function not for a special socket instance but for global socketio class? 

I learned the redis_pubsub code, it is a bit complex.

**Comment by rts-gordon** [comment]
Add a new broadcast function to implement this.
