### ISSUE TITLE
Max batch join rooms number is 16

### ISSUE THREAD

**Issue by rts-gordon** [thruster-rs/thruster-socketio#19]
Hi @trezm ,
  I  developed a batch subscribe command, and I need join more than 100 rooms in ONE subscribe command, but the MAX rooms number is 16, over 16 rooms the subscribe command will failed.
  How can I increase the MAX number to join rooms in ONE subscribe command. Thank you very much.

Subscribe command:
```
["subscribe","1-2-1:m1,1-2-1:m5,1-2-1:m15,1-2-1:m30,...]
```

Batch join rooms：
```
#[socketio_listener]
async fn join_room(mut socket: SocketIO, value: String) -> Result<(), ()> {
    if "" != value {
        debug!("join rooms: {}", value);

        let symbols: Vec<&str> = value.split(",").collect();
        for i in 0..16 {
            socket.join(&symbols[i]).await;
        }
    }

    Ok(())
}

```

**Comment by trezm** [comment]
Ahh, I see what's going on here. We have an internal broadcast channel set at a capacity of 16. My guess is this for loop adds values uninterrupted to the channel, and so the channel fills.

We have two options: 
1. Update the channel capacity [here](https://github.com/thruster-rs/thruster-socketio/blob/9a58e22ec4eeca738d03e06ef8533d82c5b2e559/socketio_middleware/src/socketio.rs#L295)
2. Change the channel to be unbounded. I recall there's a reason I didn't use one in the first place, but I can't recall right now.

Perhaps this feature would be useful as a configuration option.

**Comment by rts-gordon** [comment]
@trezm Thank you very much.
   Yes, this feature is useful for special scenario.
    What's the MAX channel capacity that I can set? 100 or 1000? Or depends on memory?
  
  Thanks again.

**Comment by rts-gordon** [comment]
Thanks for this great update.
