### ISSUE TITLE
Nginx error: upstream prematurely closed connection

### ISSUE THREAD

**Issue by CHCP** [thruster-rs/thruster-socketio#22]
hi @trezm 
   I used thruster-socketio as web socket server in my program, but there are always a lot of nginx error as follows.  And when I connected with thruster-socketio from front-end web site, after 10 or 30 minutes, the front-end will be 
 passive disconnected from server.

So how to fix this disconnection in thruster-socketio? Or is there any "keepalive" arguments can be changed in thruster-socketio?

Thank you.

Nginx error:
```
upstream prematurely closed connection while reading response header from upstream, client: 162.248.71.6

no live upstreams while connecting to upstream, client: 16.162.26.46
```

**Comment by trezm** [comment]
Fascinating -- I've actually seen this before on some of my own servers and
assumed it was something funky with my setup. I'll see if I can replicate
now. What version of thruster are you using if I might ask? Also is data
continually flowing over the websockets or are they just being kept open
with the heartbeat?

**Comment by rts-gordon** [comment]
Hi @trezm 
  Thanks for your so quick reply.
  I used the following components:
```
              Thruster: 1.1.9
              Thruster-socketio: latest
```

  If the socketio server disconnect, no data continually flowing over the websockets, and no heartbeat(PINGPING).

  Thank you.

**Comment by trezm** [comment]
Do me a favor, try 1.1.11 and see if the issue resolves. It contains a fix
for a slowloris vulnerability, and I'm wondering if connections are getting
saturated over time potentially?

**Comment by rts-gordon** [comment]
OK I will try 1.1.11
But the latest thruster-socketio depends on thruster 1.1.10, would you like to upgrade it to 1.1.11.

  And may I to know: What is the root cause of the disconnection?

  Thank you very much.

**Comment by trezm** [comment]
So, this is just a theory, as I saw it in a proxy server I was running and
it seemed to fix it.

The proxy server silently failed and dropped connections because it,
basically, was filling up it's allotted sockets and wasn't timing out any
of the connections. The update adds a solution wherein you can set a manual
expiration and you get a more reasonable error instead of silently failing.

That all being said, not sure if this will fix it or not, hopefully it
will. If not, I'll do some deep dives locally to see if I can figure out
the issue. Either way, we'll get it solved!

P.S. I absolutely should upgrade 1.1.10 to 1.1.11 :) Thanks for the heads
up! They should be compatible without changes anyway.

**Comment by rts-gordon** [comment]
Hi @trezm 
  There are no thruster 1.1.11 version on [crate.io](https://crates.io/crates/thruster/versions), would you like to push this version on it? Thanks

**Comment by trezm** [comment]
Apologies for the delay, I'll push it tonight!

**Comment by rts-gordon** [comment]
Hi @trezm 
  I am trying to upgrade thruster to 1.1.11 in Cargo.toml from github.com replace crates.io, but I found it depend on thruster-proc,  and thruster-proc can't be upgrade to 1.1.11 in Cargo.toml.  The two proc modules are confusing, why not merge them to thruster and thruster-socketio?

 Just remind kindly: the latest version are missed in crates.io:  thruster 1.1.11, thruster-proc 1.1.11, thruster-socketio 0.1.9, thruster-socketio-proc 0.1.9.

**Comment by trezm** [comment]
Apologies for the delay! thruster version 1.1.11 is now uploaded, along
with thruster-socketio 0.1.9. Please let me know if this helps fix the
issue -- otherwise I'll have to dig in further. If you can provide a
reproducible example repo that would be a huge help, otherwise I'll try my
best to replicate it locally.

**Comment by rts-gordon** [comment]
Many thanks @trezm 
I will try the latest version and let you know the result, fixed or not.

**Comment by rts-gordon** [comment]
Hi @trezm 
  I upgrade thruster to 1.1.11 and thruster-socketio to 0.1.9, but can't create web socket connection, errors as follows:

```
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: hyper::Error(User(ManualUpgrade))', C:\Users\UsersA\.cargo\registry\src\github.com-1ecc6299db9ec823\thruster-socketio-0.1.9\src\socketio_upgrade.rs:121:66
```

And would you like to update thruster to 1.1.11 in thruster-socketio/socketio_middleware dependencies together?

**Comment by trezm** [comment]
Alright, thruster is upgraded to 1.1.12, this middleware is updated to 0.1.10. Let me know if this fixes the issue -- if not we'll dig in more!

**Comment by CHCP** [comment]
Hi @trezm 
   Can you please push the latest  version thruster-socketio and thruster-socketio-proc to craters.io? 
   Because I can't reference submodule thruster-socketio-proc from github repo in Cargo.toml. 
  Thanks.

**Comment by rts-gordon** [comment]
Thanks, I am testing the latest version.

**Comment by rts-gordon** [comment]
Hi @trezm 
 Unfortunately we still have the same errors after compiled the application with the latest thruster and thruster-socketio, maybe  there are still some bugs.

My nginx configurations, reference from [Socket.io](https://socket.io/docs/v4/using-multiple-nodes/#nginx-configuration)
```
server {
       listen 80;
       listen [::]:80;

       server_name bridge.domain.com;
       location / {
       			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      			proxy_set_header Host $host;
      			proxy_pass http://ws-backend;

      			# enable WebSockets
      			proxy_http_version 1.1;
      			proxy_set_header Upgrade $http_upgrade;
      			proxy_set_header Connection "upgrade";

        }
        location ~ /\.ht {
               deny all;
        }

}

upstream ws-backend {
		hash $remote_addr consistent;
        server 127.0.0.1:3101 weight=1 max_fails=2 fail_timeout=10s;
        server 127.0.0.1:3301 weight=1 max_fails=2 fail_timeout=10s;
}
```

The same errors:
```
2022/02/02 04:24:15 [error] 46414#46414: *10123  no live upstreams while connecting to upstream, client: 172.70.210.142

2022/02/02 04:24:10 [error] 46414#46414: *10106 upstream prematurely closed connection while reading response header from upstream, client: 172.70.131.19

```

**Comment by rts-gordon** [comment]
Hi @trezm 
  I read from socket.io server options, found that thruster-socketio didn't implement this option [upgradeTimeout](https://socket.io/docs/v4/server-options/#upgradetimeout).

  I think this option is useful when establish web socket connection, would you like to implement it? Thank you.

**Comment by rts-gordon** [comment]
Hi @trezm 
  May I know any progress for the Nginx error solution? Thank you.

**Comment by trezm** [comment]
Apologies for the delay! My day job has been very busy recently. I'll
actually tackle this this weekend.

**Comment by trezm** [comment]
Finally got around to looking at this, but am unable to replicate locally. Does this only happen with nginx in front of it? If you run it without nginx does the server stop accepting connections?

**Comment by rts-gordon** [comment]
I will try it without Nginx. 

BTW,  How many sockets can be joined in a room?

Thank you.

**Comment by trezm** [comment]
That is an interesting question, I've never tested it. Theoretically it
should just be limited by machine memory and the number of sockets the os
supports I think?

**Comment by CHCP** [comment]
Functions analysis: rooms::join_channel_to_room, rooms::remove_socket_from_room.

Imagine this scenario: If socketA is leaving a room，socketB is joining this same room, will it cause data competition due to the ROOM.remove operation, which will cause the socketB joined room to fail, thus causing the connection link to fail?

**Comment by rts-gordon** [comment]
Hi @trezm 
I use Nginx load balancing to share traffic to multi socketio server, is Redis Adapter must be supported? If I don't use Redis Adapter, is this occur any errors?

**Comment by trezm** [comment]
If you're running a cluster with multiple servers, then in order for each individual instance to know about rooms and messages on other instances in the cluster, they need to have a communication method between them. That's the purpose of the Redis adapter.

If you were to run a single instance, then you wouldn't need Redis. If you're running more than one, then when Alice sends a message and it's picked up by instance A, if Bob is connected to the same room via instance B, instance A needs a way to forward that message to Bob at instance B, which is why we use redis a message queue between them.

That being said, that's a separate issue and not likely what's causing the strange remote hangups.

**Comment by trezm** [comment]
I've dug in a bit more with on of my long running instances, I thought perhaps we were exhausting file descriptors or something, but that doesn't seem to be the case either.

The ability to test this locally with any sort of tool would be _highly_ helpful!

**Comment by trezm** [comment]
Just ran a test locally against it for 10 minutes using [artillery](https://github.com/artilleryio/artillery), no luck duplicating. Are you using https on the server? Or are you relying on nginx for the SSL connection?

**Comment by rts-gordon** [comment]
I think we can replicate this 502 error in this way:
   As you know, the correct web socket call is "wss://myhost.com/socket.io/?EIO=4&transport=websocket", but if there are bad BOT or a DDOS attack, they can call like this: "http://myhost.com/socket.io/?EIO=4&transport=websocket", this will be occur a 502 error, in Nginx logs  show "upstream prematurely closed connection".

  In my local test without Nginx, I call "http://myhost.com/socket.io/?EIO=4&transport=websocket" from a browser, I got such thruster errors:
```
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidStatusCode', C:\Users\Gordon\.cargo\registry\src\github.com-1ecc6299db9ec823\thruster-1.1.14\src\context\basic_hyper_context.rs:254:68
```

the code in basic_hyper_context.rs is:
```
    fn get_response(self) -> Self::Response {
        let mut response = Response::new(self.body);

        *response.status_mut() = StatusCode::from_u16(self.status).unwrap();    //NOTES: panicked here
        *response.headers_mut() = self.headers;
        *response.version_mut() = self.http_version;

        response
    }
```

I think those two information will be useful for your more dig.

**Comment by trezm** [comment]
yes!! That's extremely helpful, thank you!

**Comment by rts-gordon** [comment]
Hi @trezm 
   I read [socketio](https://socket.io/docs/v4/) protocol, found that thruster-socketio did not implement "transport=polling". I send "transport=polling" with curl, it returned "Empty reply from server".
```
curl "http://127.0.0.1:3101/socket.io/?EIO=4&transport=polling"
```

 I setup a [socketio.js](https://github.com/socketio/socket.io) server and test the same request with curl, it returned:
```
{"sid":"miRQ0gLPyODlYLMWAAAD","upgrades":["websocket"],"pingInterval":25000,"pingTimeout":20000}
```

Will the absence of polling cause an error?  Hope this information is helpful for you.

**Comment by trezm** [comment]
All right, check out 0.1.12, it _should_ have somewhat of a fix. I don't have time to implement proper polling right now, but you can designate just websockets with `transport=websocket`. In the change though, I'm properly setting response codes and the body of the response is a more reasonable error message.

Hopefully I'll have time to properly implement polling in the future!

**Comment by rts-gordon** [comment]
Can you please publish thruster latest version to crates.io, I can't find this version on crates.io.

And would you like to change the dependence thruster to latest version in thruster-socketio Cargo.toml? I think thruster 
 the latest version fix the 502 error. Thank you.

**Comment by rts-gordon** [comment]
I download the latest version of thruster and v0.1.14 of thruster-socketio, there are some compile errors, maybe thruster changed too much to compile:
```
 handle_io_with_capacity(context, handle, message_capacity).await
    |     ----------------------- ^^^^^^^ the trait `thruster::core::context::Context` is not implemented for `BasicHyperContext`
```

**Comment by trezm** [comment]
hm, probably due to version skew -- I just updated thruster-socketio to use thruster v1.1.14, so if you upgrade the version of thruster-socketio (v0.1.13) everything should be aligned.

**Comment by rts-gordon** [comment]
That means I still can't use the latest version on Thruster(bug: Add default status code[#211](https://github.com/thruster-rs/Thruster/pull/211)). There are compile errors as above.

**Comment by rts-gordon** [comment]
test passed
