### ISSUE TITLE
Can message_capacity to be initialed in Application?

### ISSUE THREAD

**Issue by rts-gordon** [thruster-rs/thruster-socketio#24]
Hi @trezm 
  I know you gave a "message_capacity" argument to adjust the maximum number of in-flight messages, but it only can be changed in the inner function "connect_to_pubsub_with_capacity", it is Inconvenient to use.

  Can you please to change this argument to a high level, so the application can initial it for purpose use, like "connection_timeout" in Thruster? 
  Thank you.

**Comment by trezm** [comment]
We actually do have that already, check out `handle_io_with_capacity` instead of `handle_io`.

**Comment by rts-gordon** [comment]
It is good news. But I try this, there are still some error:

lib.rs does not include handle_io_with_capacity, only handle_io, so I can't call handle_io_with_capacity  in Application.

```
pub use socketio_upgrade::handle_io;
```

**Comment by trezm** [comment]
My fault!!! You're absolutely right -- I should have checked that. Should be updated in 0.1.11.

**Comment by rts-gordon** [comment]
Yes, it works.

I noticed that: the module "redis_pubsub" has the argument "message_capacity" too. If I don't call this module and only call "handle_io_with_capacity" to change the "mseeage_capacity" to 200, is there any effect to the capacity function?

**Comment by rts-gordon** [comment]
enable access redis_pubsub::connect_to_pubsub_with_capacity
