### ISSUE TITLE
Can thruster-socketio broadcast binary message?

### ISSUE THREAD

**Issue by rts-gordon** [thruster-rs/thruster-socketio#29]
Hi @trezm 
  I found that socketio::broadcast can only broadcast STRING messages, that is fine. 

  I use protocol buffer messages those need to broadcast, so is there a plan to support binary message?  That would be a useful and great feature.

**Comment by trezm** [comment]
Let me look into this a bit further, seems like a reasonable use case.

**Comment by rts-gordon** [comment]
Hi @trezm 
  May I to know: how are you going to design this feature? Add a new function like ’broadcast_binary‘ or enhance the old one 'broadcast' with Generic programming?
 
  Thank you.

**Comment by rts-gordon** [comment]
Hi @trezm 
  There is a PR for "send binary message", can you please to take a look at this and merge it? Thank you.

https://github.com/thruster-rs/thruster-socketio/pull/31

**Comment by rts-gordon** [comment]
Thanks a lot. @trezm
