### ISSUE TITLE
Can socketio remove the argument "event" in function "socketio::broadcast"

### ISSUE THREAD

**Issue by rts-gordon** [thruster-rs/thruster-socketio#30]
Hi @trezm 

  I called function "socketio::broadcast" to send messages, there are three arguments: room_id, event, message
```
pub async fn broadcast(room_id: &str, event: &str, message: &str) 
```

 I don't know what is the "event" mean, so I set "event" = "roomid",   then the Client receive message like this:
```
["event_string", "message_string"]
```

But the "event_string" is no useful for Client, so can "event" be removed from "socketio::broadcast"?  We can put all information in the "message_string" send to Client, including "event". 

Thank you.

**Comment by trezm** [comment]
This library hasn't been updated to the most recent version of socketio, so I wonder if there's something that's changed. In the past, messages were required to have an event and a message. I thought that still was the case [see here](https://socket.io/docs/v4/emitting-events/).

**Comment by rts-gordon** [comment]
Got it, thanks for your explain.
