### ISSUE TITLE
Which socket.io version does thruster-socketio implement, V3.0 or V4.0? 

### ISSUE THREAD

**Issue by rts-gordon** [thruster-rs/thruster-socketio#9]
Hi @trezm,
  Which socket.io version has thruster-socketio been implemented, V3.0 or V4.0? 

  Thank you.

**Comment by trezm** [comment]
It's currently implementing [v4](https://github.com/thruster-rs/thruster-socketio/commit/2d815a7b95bc1dde2762a77d256675f21c6e1e14#diff-37de9a35635906b46d0377ce146924b1823cb8be0fd02ac148c23b3073d7317dR149)

That being said, there might be missing pieces, so please let me know!

**Comment by CHCP** [comment]
Got it
